version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
      secrets:
        - hf_token
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=backend/main.py

secrets:
  hf_token:
    file: ./backend/hf_token.txt
